force-app/main/default/objects/External_Attendee__c/External_Attendee__c.object-meta.xml
<CustomObject>
    <label>External Attendee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/External_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>External Attendees</relationshipLabel>
    <relationshipName>External_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/External_Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Attendee__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>External Attendees</relationshipLabel>
    <relationshipName>External_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Internal_Attendee__c/Internal_Attendee__c.object-meta.xml
<CustomObject>
    <label>Internal Attendee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>User__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Attendee__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Internal Attendees</relationshipLabel>
    <relationshipName>Internal_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Internal_Attendee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Internal_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Detailed_Note__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Note__c</fullName>
    <label>Detailed Note</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MeetingController.cls
public with sharing class MeetingController {
  @AuraEnabled(cacheable=true)
  public static List<User> findUsersByName(String name) {
    List<User> userList = new List<User>();

    if (name != '') {
      String query = '%' + name + '%';
      userList = [
        SELECT Id, Name
        FROM User
        WHERE Name LIKE :query AND UserType = 'Standard'
      ];
    }

    return userList;
  }

  @AuraEnabled(cacheable=true)
  public static List<Contact> getRelatedContacts(String accountId) {
    return [SELECT Id, Name FROM Contact WHERE AccountId = :accountId];
  }

  @AuraEnabled
  public static void createInternalAttendees(
    String meetingId,
    List<User> userList
  ) {
    try {
      List<Internal_Attendee__c> attendeeList = new List<Internal_Attendee__c>();

      for (User user : userList) {
        Internal_Attendee__c attendee = new Internal_Attendee__c(
          Name = user.Name,
          User__c = user.Id,
          Meeting__c = meetingId
        );

        attendeeList.add(attendee);
      }

      insert attendeeList;
    } catch (DmlException e) {
      throw new AuraHandledException(
        'Exception occured during Attendee creation: ' + e.getMessage()
      );
    }
  }

  @AuraEnabled
  public static void createExternalAttendees(
    String meetingId,
    List<Contact> contactList
  ) {
    try {
      List<External_Attendee__c> attendeeList = new List<External_Attendee__c>();

      for (Contact contact : contactList) {
        External_Attendee__c attendee = new External_Attendee__c(
          Name = contact.Name,
          Contact__c = contact.Id,
          Meeting__c = meetingId
        );
        attendeeList.add(attendee);
      }

      insert attendeeList;
    } catch (DmlException e) {
      throw new AuraHandledException(
        'Exception occured during External Attendee creation: ' + e.getMessage()
      );
    }
  }

  @AuraEnabled
  public static void sendMeetingEmail(
    String meetingId,
    List<String> emailList
  ) {
    try {
      Meeting__c meeting = new Meeting__c();
      meeting = [
        SELECT Name, Summary__c, Meeting_Date__c, Detailed_Note__c
        FROM Meeting__c
        WHERE Id = :meetingId
        LIMIT 1
      ];

      List<Internal_Attendee__c> internalList = [
        SELECT Name, Email__c
        FROM Internal_Attendee__c
        WHERE Meeting__c = :meetingId
      ];

      List<External_Attendee__c> externalList = [
        SELECT Name, Email__c
        FROM External_Attendee__c
        WHERE Meeting__c = :meetingId
      ];

      OrgWideEmailAddress orgwideEm = new OrgWideEmailAddress();
      orgwideEm = [
        SELECT Id, DisplayName
        FROM OrgWideEmailAddress
        WHERE DisplayName = 'No-Reply'
        LIMIT 1
      ];

      List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
      if (meeting != null && !emailList.isEmpty() && orgwideEm != null) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(emailList);
        email.setOrgWideEmailAddressId(orgwideEm.id);
        email.setSubject('Meeting: ' + meeting.Name);

        String body = 'Here Are meeting details: </br>';
        body += meeting.Summary__c + '</br>';
        body += 'Meeting Date: ' + meeting.Meeting_Date__c + ' </br>';
        body += 'Meeting Details: ' + meeting.Detailed_Note__c + ' </br>';
        if (!internalList.isEmpty()) {
          body += 'Internal Attendees:' + ' </br>';
          for (Internal_Attendee__c att : internalList) {
            body += att.Name + ' ' + att.Email__c + ' </br>';
          }
        }
        if (!externalList.isEmpty()) {
          body += 'Internal Attendees:' + ' </br>';
          for (External_Attendee__c att : externalList) {
            body += att.Name + ' ' + att.Email__c + ' </br>';
          }
        }
        body += 'Best Regards';
        email.setHtmlBody(body);

        emailsToSend.add(email);
      }

      if (!emailList.isEmpty()) {
        Messaging.sendEmail(emailsToSend);
      }
    } catch (Exception e) {
      throw new AuraHandledException(
        'Exception occured while sending email ' + e.getMessage()
      );
    }
  }
}